### ISSUE TITLE
Question/Feature Request

### ISSUE THREAD

**Issue by NKM9** [gatuno/CardJitsuSnow#1]
How was the spritesheets gotten from the source images?

**Comment by gatuno** [comment]
First, you need to retrieve the tpk files from cjsnow. The tpk are gziped, but without gzip header. The result from the gzip is a file called "DPACK" format. The dpack format contains several files inside. One of the files inside the called "t" has the bitmap data, but stored in a strange flash format. I used a custom swf to load the data and save it back as a PNG. There is also a "j" file inside the dpack, which has several X,Y coordinates.

**Comment by NKM9** [comment]
Thank you so much for the answer!

**Comment by NKM9** [comment]
Next question is what program did you use to undo the gzip? I've been looking around online and not finding any specific results. Thank you so much for the help.

**Comment by gatuno** [comment]
Please stop creating issues to handle a thing not related to my game.

Bash:
printf "\x1f\x8b\x08\x00\x00\x00\x00\x00" |cat - file.tpk |gzip -dc > file.dpack

**Comment by NKM9** [comment]
I'm aware this is closed. May you please elaborate how you extracted the "t" and "j" file from the DPACK and then how the bitmap was converted to a usable swf? Sorry for the questions and if I'm wasting your time. You're apparently the only person on the internet who knows how to do this.

I noticed this repository has not gotten any new spritesheets in years, so I'll be more than willing to convert all the other spritesheets for you to use and upload them here.

**Comment by gatuno** [comment]
I understand your frustration. Search a more private way (maybe my email somewhere) to contact me and could tell you more details

**Comment by gatuno** [comment]
Leave your mail or twitter user and I will put in contact with you.

**Comment by NKM9** [comment]
My twitter is @Rbx_NKM9
Thank you so much for willing to help me out on this.
